/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.db.hibernate;
// Generated 10.10.2012 15:20:29 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConceptValueSetMembershipId generated by hbm2java
 */
@Embeddable
public class ConceptValueSetMembershipId  implements java.io.Serializable {


     private long codeSystemEntityVersionId;
     private long valuesetVersionId;

    public ConceptValueSetMembershipId() {
    }

    public ConceptValueSetMembershipId(long codeSystemEntityVersionId, long valuesetVersionId) {
       this.codeSystemEntityVersionId = codeSystemEntityVersionId;
       this.valuesetVersionId = valuesetVersionId;
    }
   

    @Column(name="codeSystemEntityVersionId", nullable=false)
    public long getCodeSystemEntityVersionId() {
        return this.codeSystemEntityVersionId;
    }
    
    public void setCodeSystemEntityVersionId(long codeSystemEntityVersionId) {
        this.codeSystemEntityVersionId = codeSystemEntityVersionId;
    }

    @Column(name="valuesetVersionId", nullable=false)
    public long getValuesetVersionId() {
        return this.valuesetVersionId;
    }
    
    public void setValuesetVersionId(long valuesetVersionId) {
        this.valuesetVersionId = valuesetVersionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConceptValueSetMembershipId) ) return false;
		 ConceptValueSetMembershipId castOther = ( ConceptValueSetMembershipId ) other; 
         
		 return (this.getCodeSystemEntityVersionId()==castOther.getCodeSystemEntityVersionId())
 && (this.getValuesetVersionId()==castOther.getValuesetVersionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCodeSystemEntityVersionId();
         result = 37 * result + (int) this.getValuesetVersionId();
         return result;
   }   


}


