/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.terminologie.db.hibernate;
// Generated 24.10.2011 10:08:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LicenceType generated by hbm2java
 */
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
@XmlRootElement
@XmlType(namespace="de.fhdo.termserver.types")
@Entity
@Table(name="licence_type"
    
)
public class LicenceType  implements java.io.Serializable {


     private Long id;
     private CodeSystemVersion codeSystemVersion;
     private String typeTxt;
     private Set<LicencedUser> licencedUsers = new HashSet<LicencedUser>(0);

    public LicenceType() {
    }

    public LicenceType(CodeSystemVersion codeSystemVersion, String typeTxt, Set<LicencedUser> licencedUsers) {
       this.codeSystemVersion = codeSystemVersion;
       this.typeTxt = typeTxt;
       this.licencedUsers = licencedUsers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codeSystemVersionId")
    public CodeSystemVersion getCodeSystemVersion() {
        return this.codeSystemVersion;
    }
    
    public void setCodeSystemVersion(CodeSystemVersion codeSystemVersion) {
        this.codeSystemVersion = codeSystemVersion;
    }
    
    @Column(name="typeTxt", length=65535)
    public String getTypeTxt() {
        return this.typeTxt;
    }
    
    public void setTypeTxt(String typeTxt) {
        this.typeTxt = typeTxt;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="licenceType")
    public Set<LicencedUser> getLicencedUsers() {
        return this.licencedUsers;
    }
    
    public void setLicencedUsers(Set<LicencedUser> licencedUsers) {
        this.licencedUsers = licencedUsers;
    }




}


