/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.terminologie.db.hibernate;
// Generated 24.10.2011 10:08:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Session generated by hbm2java
 */
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
@XmlRootElement
@XmlType(namespace="de.fhdo.termserver.types")
@Entity
@Table(name="session"
    
)
public class Session  implements java.io.Serializable {


     private Long id;
     private TermUser termUser;
     private Date lastTimestamp;
     private String sessionId;
     private String ipAddress;
     private String collabUsername;

    public Session() {
    }

	
    public Session(TermUser termUser, Date lastTimestamp, String sessionId, String collabUsername) {
        this.termUser = termUser;
        this.lastTimestamp = lastTimestamp;
        this.sessionId = sessionId;
        this.collabUsername = collabUsername;
    }
    public Session(TermUser termUser, Date lastTimestamp, String sessionId, String ipAddress, String collabUsername) {
       this.termUser = termUser;
       this.lastTimestamp = lastTimestamp;
       this.sessionId = sessionId;
       this.ipAddress = ipAddress;
       this.collabUsername = collabUsername;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="termUserId", nullable=false)
    public TermUser getTermUser() {
        return this.termUser;
    }
    
    public void setTermUser(TermUser termUser) {
        this.termUser = termUser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastTimestamp", nullable=false, length=19)
    public Date getLastTimestamp() {
        return this.lastTimestamp;
    }
    
    public void setLastTimestamp(Date lastTimestamp) {
        this.lastTimestamp = lastTimestamp;
    }
    
    @Column(name="sessionId", nullable=false, length=65535)
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    
    @Column(name="ipAddress", length=45)
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    @Column(name="collabUsername", length=65535)
    public String getCollabUsername() {
        return this.collabUsername;
    }
    
    public void setCollabUsername(String collabUsername) {
        this.collabUsername = collabUsername;
    }
}


