/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.terminologie.db.hibernate;
// Generated 24.10.2011 10:08:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TermUser generated by hbm2java
 */
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
@XmlRootElement
@XmlType(namespace="de.fhdo.termserver.types")
@Entity
@Table(name="term_user"
    
)
public class TermUser  implements java.io.Serializable {


     private Long id;
     private String name;
     private String passw;
     private boolean isAdmin;
     private String pseudonym;
     private Date activationTime;
     private Set<Session> sessions = new HashSet<Session>(0);
     private Set<LicencedUser> licencedUsers = new HashSet<LicencedUser>(0);

    public TermUser() {
    }

	
    public TermUser(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public TermUser(String name, String passw, boolean isAdmin, String pseudonym, Set<Session> sessions, Set<LicencedUser> licencedUsers) {
       this.name = name;
       this.passw = passw;
       this.isAdmin = isAdmin;
       this.pseudonym = pseudonym;
       this.sessions = sessions;
       this.licencedUsers = licencedUsers;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="passw", length=65535)
    public String getPassw() {
        return this.passw;
    }
    
    public void setPassw(String passw) {
        this.passw = passw;
    }
    
    @Column(name="isAdmin", nullable=false)
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    
    @Column(name="pseudonym", length=100)
    public String getPseudonym() {
        return this.pseudonym;
    }
    
    public void setPseudonym(String pseudonym) {
        this.pseudonym = pseudonym;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="termUser")
    public Set<Session> getSessions() {
        return this.sessions;
    }
    
    public void setSessions(Set<Session> sessions) {
        this.sessions = sessions;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="termUser")
    public Set<LicencedUser> getLicencedUsers() {
        return this.licencedUsers;
    }
    
    public void setLicencedUsers(Set<LicencedUser> licencedUsers) {
        this.licencedUsers = licencedUsers;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="activation_time", nullable=true, length=19)
    public Date getActivationTime() {
        return this.activationTime;
    }
    
    public void setActivationTime(Date activationTime) {
        this.activationTime = activationTime;
    }
}


