/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Discussiongroup generated by hbm2java
 */
@Entity
@Table(name="discussiongroup"
    
)
public class Discussiongroup  implements java.io.Serializable {


     private Long id;
     private String name;
     private Long head;
     private Set<Discussiongroupobject> discussiongroupobjects = new HashSet<Discussiongroupobject>(0);
     private Set<Collaborationuser> collaborationusers = new HashSet<Collaborationuser>(0);
     private Set<Privilege> privileges = new HashSet<Privilege>(0);

    public Discussiongroup() {
    }

	
    public Discussiongroup(String name) {
        this.name = name;
    }
    public Discussiongroup(String name, Long head, Set<Discussiongroupobject> discussiongroupobjects, Set<Collaborationuser> collaborationusers, Set<Privilege> privileges) {
       this.name = name;
       this.head = head;
       this.discussiongroupobjects = discussiongroupobjects;
       this.collaborationusers = collaborationusers;
       this.privileges = privileges;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=32)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="head")
    public Long getHead() {
        return this.head;
    }
    
    public void setHead(Long head) {
        this.head = head;
    }
    
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="discussiongroup")
    public Set<Discussiongroupobject> getDiscussiongroupobjects() {
        return this.discussiongroupobjects;
    }
    
    public void setDiscussiongroupobjects(Set<Discussiongroupobject> discussiongroupobjects) {
        this.discussiongroupobjects = discussiongroupobjects;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="discussiongroup2collaborationuser", joinColumns = { 
        @JoinColumn(name="discussionGroupId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="collaborationuserId", nullable=false, updatable=false) })
    public Set<Collaborationuser> getCollaborationusers() {
        return this.collaborationusers;
    }
    
    public void setCollaborationusers(Set<Collaborationuser> collaborationusers) {
        this.collaborationusers = collaborationusers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="discussiongroup")
    public Set<Privilege> getPrivileges() {
        return this.privileges;
    }
    
    public void setPrivileges(Set<Privilege> privileges) {
        this.privileges = privileges;
    }
}


