/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package de.fhdo.terminologie.db.hibernate;
// Generated 24.10.2011 10:08:21 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CodeSystem generated by hbm2java
 */
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement
@XmlType(namespace = "de.fhdo.termserver.types")
@Entity
@Table(name = "code_system")
public class CodeSystem implements java.io.Serializable
{

  private Long id;
  private Long currentVersionId;
  private String name;
  private String description;
  private String descriptionEng;
  private Date insertTimestamp;
  private String codeSystemType;
  private String website;
  private Boolean autoRelease = false;
  private Boolean incompleteCS = false;
  private String responsibleOrganization;
  private Set<CodeSystemVersion> codeSystemVersions = new HashSet<CodeSystemVersion>(0);
  private Set<DomainValue> domainValues = new HashSet<DomainValue>(0);
  private Set<MetadataParameter> metadataParameters = new HashSet<MetadataParameter>(0);

  public CodeSystem()
  {
  }

  public CodeSystem(String name, Date insertTimestamp)
  {
    this.name = name;
    this.insertTimestamp = insertTimestamp;
  }

  public CodeSystem(Long currentVersionId, String name, String description, Date insertTimestamp, String descriptionEng, String codeSystemType, String website, Set<CodeSystemVersion> codeSystemVersions, Set<DomainValue> domainValues)
  {
    this.currentVersionId = currentVersionId;
    this.name = name;
    this.description = description;
    this.descriptionEng = descriptionEng;
    this.insertTimestamp = insertTimestamp;
    this.codeSystemType = codeSystemType;
    this.website = website;
    this.codeSystemVersions = codeSystemVersions;
    this.domainValues = domainValues;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
  public Long getId()
  {
    return this.id;
  }

  public void setId(Long id)
  {
    this.id = id;
  }

  @Column(name = "currentVersionId")
  public Long getCurrentVersionId()
  {
    return this.currentVersionId;
  }

  public void setCurrentVersionId(Long currentVersionId)
  {
    this.currentVersionId = currentVersionId;
  }

  @Column(name = "name", nullable = false, length = 100)
  public String getName()
  {
    return this.name;
  }

  public void setName(String name)
  {
    this.name = name;
  }

  @Column(name = "description", length = 65535)
  public String getDescription()
  {
    return this.description;
  }

  public void setDescription(String description)
  {
    this.description = description;
  }
  
  @Column(name = "descriptionEng", length = 65535)
  public String getDescriptionEng()
  {
    return this.descriptionEng;
  }

  public void setDescriptionEng(String descriptionEng)
  {
    this.descriptionEng = descriptionEng;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "insertTimestamp", nullable = false, length = 19)
  public Date getInsertTimestamp()
  {
    return this.insertTimestamp;
  }

  public void setInsertTimestamp(Date insertTimestamp)
  {
    this.insertTimestamp = insertTimestamp;
  }
  
  @Column(name = "codeSystemType", length = 30)
  public String getCodeSystemType()
  {
    return this.codeSystemType;
  }

  public void setCodeSystemType(String codeSystemType)
  {
    this.codeSystemType = codeSystemType;
  }
	
	@Column(name="incompleteCS")
	public Boolean getIncompleteCS() {
			return this.incompleteCS;
	}

	public void setIncompleteCS(Boolean incompleteCS) {
			this.incompleteCS = incompleteCS;
	}

	@Column(name="responsibleOrganization", length=65535)
	public String getResponsibleOrganization() {
			return this.responsibleOrganization;
	}

	public void setResponsibleOrganization(String responsibleOrganization) {
			this.responsibleOrganization = responsibleOrganization;
	}

  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "codeSystem")
	public Set<CodeSystemVersion> getCodeSystemVersions()
	{
		return this.codeSystemVersions;
	}

	public void setCodeSystemVersions(Set<CodeSystemVersion> codeSystemVersions)
	{
		this.codeSystemVersions = codeSystemVersions;
	}

  
  @Column(name = "website", length = 65535)
  public String getWebsite() {
      return website;
  }

  public void setWebsite(String website) {
      this.website = website;
  }
  
  @Column(name = "autoRelease", nullable = false)
  public boolean getAutoRelease() {
      return this.autoRelease;
  }

  public void setAutoRelease(boolean autoRelease) {
      this.autoRelease = autoRelease;
  }

  @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
  @JoinTable(name = "domain_value_has_code_system", joinColumns =
  {
    @JoinColumn(name = "code_system_id", nullable = false, updatable = false)
  }, inverseJoinColumns =
  {
    @JoinColumn(name = "domain_value_domainValueId", nullable = false, updatable = false)
  })
  public Set<DomainValue> getDomainValues()
  {
    return this.domainValues;
  }

  public void setDomainValues(Set<DomainValue> domainValues)
  {
    this.domainValues = domainValues;
  }

  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "codeSystem")
  public Set<MetadataParameter> getMetadataParameters()
  {
    return this.metadataParameters;
  }

  public void setMetadataParameters(Set<MetadataParameter> metadataParameters)
  {
    this.metadataParameters = metadataParameters;
  }
  
  @Override
    public String toString(){
        String s = super.toString();

        return "CS: " + name + "("+s+")";
    }
}
