/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.terminologie.db.hibernate;
// Generated 24.10.2011 10:08:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LicencedUser generated by hbm2java
 */
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
@XmlRootElement
@XmlType(namespace="de.fhdo.termserver.types")
@Entity
@Table(name="licenced_user"
    
)
public class LicencedUser  implements java.io.Serializable {


     private LicencedUserId id;
     private LicenceType licenceType;
     private CodeSystemVersion codeSystemVersion;
     private TermUser termUser;
     private Date validFrom;
     private Date validTo;

    public LicencedUser() {
    }

	
    public LicencedUser(LicencedUserId id, CodeSystemVersion codeSystemVersion, TermUser termUser, Date validFrom, Date validTo) {
        this.id = id;
        this.codeSystemVersion = codeSystemVersion;
        this.termUser = termUser;
        this.validFrom = validFrom;
        this.validTo = validTo;
    }
    public LicencedUser(LicencedUserId id, LicenceType licenceType, CodeSystemVersion codeSystemVersion, TermUser termUser, Date validFrom, Date validTo) {
       this.id = id;
       this.licenceType = licenceType;
       this.codeSystemVersion = codeSystemVersion;
       this.termUser = termUser;
       this.validFrom = validFrom;
       this.validTo = validTo;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="userId", nullable=false) ), 
        @AttributeOverride(name="codeSystemVersionId", column=@Column(name="codeSystemVersionId", nullable=false) ) } )
    public LicencedUserId getId() {
        return this.id;
    }
    
    public void setId(LicencedUserId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="licenceTypeId")
    public LicenceType getLicenceType() {
        return this.licenceType;
    }
    
    public void setLicenceType(LicenceType licenceType) {
        this.licenceType = licenceType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codeSystemVersionId", nullable=false, insertable=false, updatable=false)
    public CodeSystemVersion getCodeSystemVersion() {
        return this.codeSystemVersion;
    }
    
    public void setCodeSystemVersion(CodeSystemVersion codeSystemVersion) {
        this.codeSystemVersion = codeSystemVersion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userId", nullable=false, insertable=false, updatable=false)
    public TermUser getTermUser() {
        return this.termUser;
    }
    
    public void setTermUser(TermUser termUser) {
        this.termUser = termUser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="validFrom", nullable=false, length=19)
    public Date getValidFrom() {
        return this.validFrom;
    }
    
    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="validTo", nullable=false, length=19)
    public Date getValidTo() {
        return this.validTo;
    }
    
    public void setValidTo(Date validTo) {
        this.validTo = validTo;
    }




}


