/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.db.hibernate;
// Generated 10.10.2012 15:20:29 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Domain generated by hbm2java
 */
@Entity
@Table(name="domain"
    
)
public class Domain  implements java.io.Serializable {


     private Long domainId;
     private String domainName;
     private String domainOid;
     private String description;
     private String displayText;
     private Boolean isOptional;
     private String defaultValue;
     private String domainType;
     private Long displayOrder;
     private Set<DomainValue> domainValues = new HashSet<DomainValue>(0);

    public Domain() {
    }

	
    public Domain(String domainName) {
        this.domainName = domainName;
    }
    public Domain(String domainName, String domainOid, String description, String displayText, Boolean isOptional, String defaultValue, String domainType, Long displayOrder, Set<DomainValue> domainValues) {
       this.domainName = domainName;
       this.domainOid = domainOid;
       this.description = description;
       this.displayText = displayText;
       this.isOptional = isOptional;
       this.defaultValue = defaultValue;
       this.domainType = domainType;
       this.displayOrder = displayOrder;
       this.domainValues = domainValues;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="domainId", unique=true, nullable=false)
    public Long getDomainId() {
        return this.domainId;
    }
    
    public void setDomainId(Long domainId) {
        this.domainId = domainId;
    }
    
    @Column(name="domainName", nullable=false, length=50)
    public String getDomainName() {
        return this.domainName;
    }
    
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }
    
    @Column(name="domainOid", length=50)
    public String getDomainOid() {
        return this.domainOid;
    }
    
    public void setDomainOid(String domainOid) {
        this.domainOid = domainOid;
    }
    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="displayText", length=65535)
    public String getDisplayText() {
        return this.displayText;
    }
    
    public void setDisplayText(String displayText) {
        this.displayText = displayText;
    }
    
    @Column(name="isOptional")
    public Boolean getIsOptional() {
        return this.isOptional;
    }
    
    public void setIsOptional(Boolean isOptional) {
        this.isOptional = isOptional;
    }
    
    @Column(name="defaultValue", length=60)
    public String getDefaultValue() {
        return this.defaultValue;
    }
    
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }
    
    @Column(name="domainType", length=50)
    public String getDomainType() {
        return this.domainType;
    }
    
    public void setDomainType(String domainType) {
        this.domainType = domainType;
    }
    
    @Column(name="displayOrder")
    public Long getDisplayOrder() {
        return this.displayOrder;
    }
    
    public void setDisplayOrder(Long displayOrder) {
        this.displayOrder = displayOrder;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="domain")
    public Set<DomainValue> getDomainValues() {
        return this.domainValues;
    }
    
    public void setDomainValues(Set<DomainValue> domainValues) {
        this.domainValues = domainValues;
    }




}


