/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proposalstatuschange generated by hbm2java
 */
@Entity
@Table(name="proposalstatuschange"
    
)
public class Proposalstatuschange  implements java.io.Serializable {


     private Long id;
     private Proposal proposal;
     private Collaborationuser collaborationuser;
     private int proposalStatusFrom;
     private int proposalStatusTo;
     private Date changeTimestamp;
     private String reason;

    public Proposalstatuschange() {
    }

	
    public Proposalstatuschange(Proposal proposal, Collaborationuser collaborationuser, int proposalStatusFrom, int proposalStatusTo, Date changeTimestamp) {
        this.proposal = proposal;
        this.collaborationuser = collaborationuser;
        this.proposalStatusFrom = proposalStatusFrom;
        this.proposalStatusTo = proposalStatusTo;
        this.changeTimestamp = changeTimestamp;
    }
    public Proposalstatuschange(Proposal proposal, Collaborationuser collaborationuser, int proposalStatusFrom, int proposalStatusTo, Date changeTimestamp, String reason) {
       this.proposal = proposal;
       this.collaborationuser = collaborationuser;
       this.proposalStatusFrom = proposalStatusFrom;
       this.proposalStatusTo = proposalStatusTo;
       this.changeTimestamp = changeTimestamp;
       this.reason = reason;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proposalId", nullable=false)
    public Proposal getProposal() {
        return this.proposal;
    }
    
    public void setProposal(Proposal proposal) {
        this.proposal = proposal;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="collaborationUserId", nullable=false)
    public Collaborationuser getCollaborationuser() {
        return this.collaborationuser;
    }
    
    public void setCollaborationuser(Collaborationuser collaborationuser) {
        this.collaborationuser = collaborationuser;
    }
    
    @Column(name="proposalStatusFrom", nullable=false)
    public int getProposalStatusFrom() {
        return this.proposalStatusFrom;
    }
    
    public void setProposalStatusFrom(int proposalStatusFrom) {
        this.proposalStatusFrom = proposalStatusFrom;
    }
    
    @Column(name="proposalStatusTo", nullable=false)
    public int getProposalStatusTo() {
        return this.proposalStatusTo;
    }
    
    public void setProposalStatusTo(int proposalStatusTo) {
        this.proposalStatusTo = proposalStatusTo;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="changeTimestamp", nullable=false, length=19)
    public Date getChangeTimestamp() {
        return this.changeTimestamp;
    }
    
    public void setChangeTimestamp(Date changeTimestamp) {
        this.changeTimestamp = changeTimestamp;
    }
    
    @Column(name="reason", length=65535)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }




}


