/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Privilege generated by hbm2java
 */
@Entity
@Table(name="privilege"
    
)
public class Privilege  implements java.io.Serializable {


     private Long id;
     private Proposal proposal;
     private Collaborationuser collaborationuser;
     private Discussiongroup discussiongroup;
     private Date fromDate;
     private Boolean mayChangeStatus;
     private Boolean mayManageObjects;
     private Boolean sendMail;

    public Privilege() {
    }

	
    public Privilege(Discussiongroup discussiongroup, Date fromDate) {
        this.discussiongroup = discussiongroup;
        this.fromDate = fromDate;
    }
    public Privilege(Proposal proposal, Collaborationuser collaborationuser, Discussiongroup discussiongroup, Date fromDate, Boolean mayChangeStatus, Boolean mayManageObjects, Boolean sendMail) {
       this.proposal = proposal;
       this.collaborationuser = collaborationuser;
       this.discussiongroup = discussiongroup;
       this.fromDate = fromDate;
       this.mayChangeStatus = mayChangeStatus;
       this.mayManageObjects = mayManageObjects;
       this.sendMail = sendMail;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proposalId")
    public Proposal getProposal() {
        return this.proposal;
    }
    
    public void setProposal(Proposal proposal) {
        this.proposal = proposal;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="collaborationUserId")
    public Collaborationuser getCollaborationuser() {
        return this.collaborationuser;
    }
    
    public void setCollaborationuser(Collaborationuser collaborationuser) {
        this.collaborationuser = collaborationuser;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="discussionGroupId")
    public Discussiongroup getDiscussiongroup() {
        return this.discussiongroup;
    }
    
    public void setDiscussiongroup(Discussiongroup discussiongroup) {
        this.discussiongroup = discussiongroup;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fromDate", nullable=false, length=19)
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    
    @Column(name="mayChangeStatus")
    public Boolean getMayChangeStatus() {
        return this.mayChangeStatus;
    }
    
    public void setMayChangeStatus(Boolean mayChangeStatus) {
        this.mayChangeStatus = mayChangeStatus;
    }
    
    @Column(name="mayManageObjects")
    public Boolean getMayManageObjects() {
        return this.mayManageObjects;
    }
    
    public void setMayManageObjects(Boolean mayManageObjects) {
        this.mayManageObjects = mayManageObjects;
    }
    
    @Column(name="sendMail")
    public Boolean getSendMail() {
        return this.sendMail;
    }
    
    public void setSendMail(Boolean sendMail) {
        this.sendMail = sendMail;
    }




}


