/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(name="rating"
    
)
public class Rating  implements java.io.Serializable {


     private Long id;
     private Discussion discussion;
     private Proposal proposal;
     private Collaborationuser collaborationuser;
     private Integer negative;
     private Integer positive;
     private String text;
     private Integer value;

    public Rating() {
    }

	
    public Rating(Discussion discussion, Collaborationuser collaborationuser) {
        this.discussion = discussion;
        this.collaborationuser = collaborationuser;
    }
    public Rating(Discussion discussion, Proposal proposal, Collaborationuser collaborationuser, Integer negative, Integer positive, String text, Integer value) {
       this.discussion = discussion;
       this.proposal = proposal;
       this.collaborationuser = collaborationuser;
       this.negative = negative;
       this.positive = positive;
       this.text = text;
       this.value = value;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="discussionId")
    public Discussion getDiscussion() {
        return this.discussion;
    }
    
    public void setDiscussion(Discussion discussion) {
        this.discussion = discussion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proposalId")
    public Proposal getProposal() {
        return this.proposal;
    }
    
    public void setProposal(Proposal proposal) {
        this.proposal = proposal;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="collaborationUserId", nullable=false)
    public Collaborationuser getCollaborationuser() {
        return this.collaborationuser;
    }
    
    public void setCollaborationuser(Collaborationuser collaborationuser) {
        this.collaborationuser = collaborationuser;
    }
    
    @Column(name="negative")
    public Integer getNegative() {
        return this.negative;
    }
    
    public void setNegative(Integer negative) {
        this.negative = negative;
    }
    
    @Column(name="positive")
    public Integer getPositive() {
        return this.positive;
    }
    
    public void setPositive(Integer positive) {
        this.positive = positive;
    }
    
    @Column(name="text", length=65535)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    
    @Column(name="value")
    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }




}


