/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    
)
public class Role  implements java.io.Serializable {

     private Long id;
     private Boolean adminFlag;
     private String name;
     private Set<Status> statuses = new HashSet<Status>(0);
     private Set<Collaborationuser> collaborationusers = new HashSet<Collaborationuser>(0);
     private Set<Statusrel> statusrels = new HashSet<Statusrel>(0);

    public Role() {
    }

    public Role(Boolean adminFlag, String name, Set<Status> statuses, Set<Collaborationuser> collaborationusers, Set<Statusrel> statusrels) {
       this.adminFlag = adminFlag;
       this.name = name;
       this.statuses = statuses;
       this.collaborationusers = collaborationusers;
       this.statusrels = statusrels;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="adminFlag")
    public Boolean getAdminFlag() {
        return this.adminFlag;
    }
    
    public void setAdminFlag(Boolean adminFlag) {
        this.adminFlag = adminFlag;
    }
    
    @Column(name="name", length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="role2status", joinColumns = { 
        @JoinColumn(name="roleId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="statusId", nullable=false, updatable=false) })
    public Set<Status> getStatuses() {
        return this.statuses;
    }
    
    public void setStatuses(Set<Status> statuses) {
        this.statuses = statuses;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="role2collaborationuser", joinColumns = { 
        @JoinColumn(name="roleId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="collaborationUserId", nullable=false, updatable=false) })
    public Set<Collaborationuser> getCollaborationusers() {
        return this.collaborationusers;
    }
    
    public void setCollaborationusers(Set<Collaborationuser> collaborationusers) {
        this.collaborationusers = collaborationusers;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="role2action", joinColumns = { 
        @JoinColumn(name="roleId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="statusRelId", nullable=false, updatable=false) })
    public Set<Statusrel> getStatusrels() {
        return this.statusrels;
    }
    
    public void setStatusrels(Set<Statusrel> statusrels) {
        this.statusrels = statusrels;
    }




}


