/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.db.hibernate;
// Generated 24.10.2011 10:08:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ValueSetVersion generated by hbm2java
 */
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
@XmlRootElement
@XmlType(namespace="de.fhdo.termserver.idp.types")
@Entity
@Table(name="value_set_version"
    
)
public class ValueSetVersion  implements java.io.Serializable {


     private Long versionId;
     private ValueSet valueSet;
     private Integer status;
     private Date statusDate;
     private Date insertTimestamp;
     private Date releaseDate;
     private Date lastChangeDate;
     private Long previousVersionId;
     private Long preferredLanguageId;
     private String oid;
     private String name;
     private Long validityRange;
     private Set<ConceptValueSetMembership> conceptValueSetMemberships = new HashSet<ConceptValueSetMembership>(0);

    public ValueSetVersion() {
    }

	
    public ValueSetVersion(ValueSet valueSet, Date statusDate, Date insertTimestamp) {
        this.valueSet = valueSet;
        this.statusDate = statusDate;
        this.insertTimestamp = insertTimestamp;
    }
    public ValueSetVersion(ValueSet valueSet, Integer status, Date statusDate, Date insertTimestamp, Date releaseDate, Date lastChangeDate, String name, Long previousVersionId, Long preferredLanguageId, String oid, Long validityRange, Set<ConceptValueSetMembership> conceptValueSetMemberships) {
       this.valueSet = valueSet;
       this.status = status;
       this.statusDate = statusDate;
       this.insertTimestamp = insertTimestamp;
       this.releaseDate = releaseDate;
       this.lastChangeDate = lastChangeDate;
       this.previousVersionId = previousVersionId;
       this.preferredLanguageId = preferredLanguageId;
       this.oid=oid;
       this.validityRange = validityRange;
       this.conceptValueSetMemberships = conceptValueSetMemberships;
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="versionId", unique=true, nullable=false)
    public Long getVersionId() {
        return this.versionId;
    }
    
    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="valueSetId", nullable=false)
    public ValueSet getValueSet() {
        return this.valueSet;
    }
    
    public void setValueSet(ValueSet valueSet) {
        this.valueSet = valueSet;
    }
    
    @Column(name = "name", nullable = false, length = 100)
    public String getName()
    {
      return this.name;
    }

    public void setName(String name)
    {
      this.name = name;
    }
    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="statusDate", nullable=false, length=19)
    public Date getStatusDate() {
        return this.statusDate;
    }
    
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastChangeDate", length=19)
    public Date getLastChangeDate() {
        return this.lastChangeDate;
    }
    
    public void setLastChangeDate(Date lastChangeDate) {
        this.lastChangeDate = lastChangeDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="insertTimestamp", nullable=false, length=19)
    public Date getInsertTimestamp() {
        return this.insertTimestamp;
    }
    
    public void setInsertTimestamp(Date insertTimestamp) {
        this.insertTimestamp = insertTimestamp;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="releaseDate", length=19)
    public Date getReleaseDate() {
        return this.releaseDate;
    }
    
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }
    
    @Column(name="previousVersionId")
    public Long getPreviousVersionId() {
        return this.previousVersionId;
    }
    
    public void setPreviousVersionId(Long previousVersionId) {
        this.previousVersionId = previousVersionId;
    }
    
    @Column(name="preferredLanguageId")
    public Long getPreferredLanguageId() {
        return this.preferredLanguageId;
    }
    
    public void setPreferredLanguageId(Long preferredLanguageId) {
        this.preferredLanguageId = preferredLanguageId;
    }
    
    @Column(name="oid", length=100)
    public String getOid() {
        return this.oid;
    }
    
    public void setOid(String oid) {
        this.oid = oid;
    }
    
    @Column(name="validityRange")
    public Long getValidityRange() {
        return this.validityRange;
    }
    
    public void setValidityRange(Long validityRange) {
        this.validityRange = validityRange;
    }
    
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="valueSetVersion")
    public Set<ConceptValueSetMembership> getConceptValueSetMemberships() {
        return this.conceptValueSetMemberships;
    }
    
    public void setConceptValueSetMemberships(Set<ConceptValueSetMembership> conceptValueSetMemberships) {
        this.conceptValueSetMemberships = conceptValueSetMemberships;
    }




}


