/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Collaborationuser generated by hbm2java
 */
@Entity
@Table(name = "enquiry")
public class Enquiry implements java.io.Serializable
{

  private Long id;
  private Collaborationuser collaborationuser;
  private String requestType;
  private String requestDescription;
  private String termName;
  private String termDescription;
  private String intendedValidityRange;
  private Collaborationuser collaborationuserExtPerson;
  private Boolean closedFlag;

  public Enquiry()
  {
  }

  public Enquiry(Long id, Collaborationuser collaborationuser, String requestType, String requestDescription, String termName, String termDescription, String intendedValidityRange, Collaborationuser collaborationuserExtPerson, Boolean closedFlag)
  {
    this.id = id;
    this.collaborationuser = collaborationuser;
    this.requestType = requestType;
    this.requestDescription = requestDescription;
    this.termName = termName;
    this.termDescription = termDescription;
    this.intendedValidityRange = intendedValidityRange;
    this.collaborationuserExtPerson = collaborationuserExtPerson;
    this.closedFlag = closedFlag;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
  public Long getId()
  {
    return this.id;
  }

  public void setId(Long id)
  {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "collaborationUserId", nullable=false)
  public Collaborationuser getCollaborationuser()
  {
    return this.collaborationuser;
  }

  public void setCollaborationuser(Collaborationuser collaborationuser)
  {
    this.collaborationuser = collaborationuser;
  }

  @Column(name = "requestType", nullable = false, length = 100)
  public String getRequestType()
  {
    return this.requestType;
  }

  public void setRequestType(String requestType)
  {
    this.requestType = requestType;
  }
  
  @Column(name = "requestDescription", nullable = false, length = 65535)
  public String getRequestDescription()
  {
    return this.requestDescription;
  }

  public void setRequestDescription(String requestDescription)
  {
    this.requestDescription = requestDescription;
  }

  @Column(name = "termName", length = 100)
  public String getTermName()
  {
    return this.termName;
  }

  public void setTermName(String termName)
  {
    this.termName = termName;
  }

  @Column(name = "termDescription", length = 65535)
  public String getTermDescription()
  {
    return this.termDescription;
  }

  public void setTermDescription(String termDescription)
  {
    this.termDescription = termDescription;
  }

  @Column(name = "intendedValidityRange", length = 100)
  public String getIntendedValidityRange()
  {
    return this.intendedValidityRange;
  }

  public void setIntendedValidityRange(String intendedValidityRange)
  {
    this.intendedValidityRange = intendedValidityRange;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "extPerson")
  public Collaborationuser getCollaborationuserExtPerson()
  {
    return this.collaborationuserExtPerson;
  }

  public void setCollaborationuserExtPerson(Collaborationuser collaborationuserExtPerson)
  {
    this.collaborationuserExtPerson = collaborationuserExtPerson;
  }
  
  @Column(name="closedFlag")
  public Boolean getClosedFlag() {
      return this.closedFlag;
  }
    
  public void setClosedFlag(Boolean closedFlag) {
      this.closedFlag = closedFlag;
  }
}
