/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Quote generated by hbm2java
 */
@Entity
@Table(name="quote"
    
)
public class Quote  implements java.io.Serializable {


     private Long id;
     private Discussion discussionByDiscussionId;
     private Discussion discussionByDiscussionIdQuoted;
     private String text;

    public Quote() {
    }

    public Quote(Discussion discussionByDiscussionId, Discussion discussionByDiscussionIdQuoted, String text) {
       this.discussionByDiscussionId = discussionByDiscussionId;
       this.discussionByDiscussionIdQuoted = discussionByDiscussionIdQuoted;
       this.text = text;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="discussionId")
    public Discussion getDiscussionByDiscussionId() {
        return this.discussionByDiscussionId;
    }
    
    public void setDiscussionByDiscussionId(Discussion discussionByDiscussionId) {
        this.discussionByDiscussionId = discussionByDiscussionId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="discussionIdQuoted")
    public Discussion getDiscussionByDiscussionIdQuoted() {
        return this.discussionByDiscussionIdQuoted;
    }
    
    public void setDiscussionByDiscussionIdQuoted(Discussion discussionByDiscussionIdQuoted) {
        this.discussionByDiscussionIdQuoted = discussionByDiscussionIdQuoted;
    }
    
    @Column(name="text", length=65535)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


