/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2013 FH Dortmund: Peter Haas, Robert Muetzner
 * government-funded by the Ministry of Health of Germany
 * government-funded by the Ministry of Health, Equalities, Care and Ageing of North Rhine-Westphalia and the European Union
 * 
 * This program is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
 * for more details.
 *  
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SysParam generated by hbm2java
 */
@Entity
@Table(name="sys_param"
    
)
public class SysParam  implements java.io.Serializable {


     private Long id;
     private DomainValue domainValueByValidityDomain;
     private DomainValue domainValueByModifyLevel;
     private String name;
     private Long objectId;
     private String javaDatatype;
     private String value;
     private String description;

    public SysParam() {
    }

	
    public SysParam(String name) {
        this.name = name;
    }
    public SysParam(DomainValue domainValueByValidityDomain, DomainValue domainValueByModifyLevel, String name, Long objectId, String javaDatatype, String value, String description) {
       this.domainValueByValidityDomain = domainValueByValidityDomain;
       this.domainValueByModifyLevel = domainValueByModifyLevel;
       this.name = name;
       this.objectId = objectId;
       this.javaDatatype = javaDatatype;
       this.value = value;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="validity_domain")
    public DomainValue getDomainValueByValidityDomain() {
        return this.domainValueByValidityDomain;
    }
    
    public void setDomainValueByValidityDomain(DomainValue domainValueByValidityDomain) {
        this.domainValueByValidityDomain = domainValueByValidityDomain;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="modify_level")
    public DomainValue getDomainValueByModifyLevel() {
        return this.domainValueByModifyLevel;
    }
    
    public void setDomainValueByModifyLevel(DomainValue domainValueByModifyLevel) {
        this.domainValueByModifyLevel = domainValueByModifyLevel;
    }
    
    @Column(name="name", nullable=false, length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="object_id")
    public Long getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }
    
    @Column(name="java_datatype", length=65535)
    public String getJavaDatatype() {
        return this.javaDatatype;
    }
    
    public void setJavaDatatype(String javaDatatype) {
        this.javaDatatype = javaDatatype;
    }
    
    @Column(name="value", length=65535)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


